### ISSUE TITLE
World buff alarm: Idea for quick classic wow addon

### ISSUE THREAD

**Issue by JohnEU** [RagedUnicorn/wow-pvpwarn#5]
Hi,

I had an idea for a quick addon that seems to be missing in wow classic atm. I think the functionality might be similar to this, which Is why is post the idea here. No idea how easy it would be to do.

**The idea:** An voice/sound announcer for when world buffs are incoming in classic wow such as Ony head or blessing from leader of horde/alliance.

Reason: Many people are logged out on their alt with songflower, soon DM buffs etc. waiting for the Ony head to get dropped for example. The issue is that you cannot go afk, because you only have a few seconds after the quest is handed in to log on main and get the buffs.

There is an announcement text in chat that all in the main city can see before the world buff comes. Hence, if one can scan for this, and then announce with sound one can more easily go afk.

Let me know what you think :)

**Comment by RagedUnicorn** [comment]
Hi @JohnEU 

Sorry didn't see this for a long time because I no longer develop this any further. I'm currently working on the classic version of this addon. I think the idea is a very good idea but is already done in deadly-boss-mods (in the meantime). I think almost any serious pve raider has deadly-boss-mods installed and thus not necessary to add this to this addon as well.

https://www.curseforge.com/wow/addons/deadly-boss-mods

Cheers,
RagedUnicorn
